In [1]:
import numpy as np # linear algebra
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
df=pd.read_csv("/content/Retail and wherehouse Sale.csv")

In [5]:
df_rs=pd.read_csv("/content/Retail_sales.csv")

In [40]:
df.info()
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   YEAR              30000 non-null  int64
 1   MONTH             30000 non-null  int64
 2   SUPPLIER          29967 non-null  object
 3   ITEM CODE         30000 non-null  object
 4   ITEM DESCRIPTION  30000 non-null  object
 5   ITEM TYPE         30000 non-null  object
 6   RETAIL SALES      29999 non-null  float64
 7   RETAIL TRANSFERS  30000 non-null  float64
 8   WAREHOUSE SALES   30000 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 2.1+ MB

YEAR                    1
MONTH                   4
SUPPLIER              290
ITEM CODE           15668
ITEM DESCRIPTION    15732
ITEM TYPE               8
RETAIL SALES         3657
RETAIL TRANSFERS      542
WAREHOUSE SALES      1032
dtype: int64

In [41]:
df.head(2)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.0,0.0,2.0
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.0,1.0,4.0

In [42]:
df.describe()

          YEAR         MONTH  RETAIL SALES  RETAIL TRANSFERS  WAREHOUSE SALES
count  30000.0  30000.000000  29999.000000      30000.000000     30000.000000
mean    2020.0      3.911467      6.939796          6.594058        27.431031
std        0.0      2.836788     33.081054         27.879428       272.166085
min     2020.0      1.000000     -0.420000         -6.000000     -3999.000000
25%     2020.0      1.000000      0.000000          0.000000         0.000000
50%     2020.0      3.000000      0.160000          0.000000         1.000000
75%     2020.0      7.000000      2.920000          3.000000         6.000000
max     2020.0      9.000000   2739.000000       1507.000000     18317.000000

In [43]:
df.isnull().sum()

YEAR                 0
MONTH                0
SUPPLIER            33
ITEM CODE            0
ITEM DESCRIPTION     0
ITEM TYPE            0
RETAIL SALES         1
RETAIL TRANSFERS     0
WAREHOUSE SALES      0
dtype: int64

In [44]:
df = df.dropna() #drop null rows

In [45]:
df = df.drop_duplicates() # drop duplicates

In [46]:
df.to_csv('Wholesale_final.csv', index=False)

In [28]:
df_rs.info()
df_rs.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store ID               30000 non-null  object
 1   Product ID             30000 non-null  int64
 2   Date                   30000 non-null  object
 3   Units Sold             30000 non-null  int64
 4   Sales Revenue (USD)    30000 non-null  float64
 5   Discount Percentage    30000 non-null  int64
 6   Marketing Spend (USD)  30000 non-null  int64
 7   Store Location         30000 non-null  object
 8   Product Category       30000 non-null  object
 9   Day of the Week        30000 non-null  object
 10  Holiday Effect         30000 non-null  bool
dtypes: bool(1), float64(1), int64(4), object(5)
memory usage: 2.3+ MB

Store ID                    1
Product ID                 42
Date                      731
Units Sold                 32
Sales Revenue (USD)      2545
Discount Percentage         5
Marketing Spend (USD)     200
Store Location            243
Product Category            4
Day of the Week             7
Holiday Effect              2
dtype: int64

In [29]:
df_rs.head(3)

,Store ID,Product ID,Date,Units Sold,Sales Revenue (USD),Discount Percentage,Marketing Spend (USD),Store Location,Product Category,Day of the Week,Holiday Effect
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False

In [30]:
df_rs.tail(3)

,Store ID,Product ID,Date,Units Sold,Sales Revenue (USD),Discount Percentage,Marketing Spend (USD),Store Location,Product Category,Day of the Week,Holiday Effect
29997,Spearsland,50239115,2022-01-27,6,3001.38,0,0,South Georgia and the South Sandwich Islands,Clothing,Thursday,False
29998,Spearsland,50239115,2022-01-28,5,2501.15,0,0,Haiti,Clothing,Friday,False
29999,Spearsland,50239115,2022-01-29,3,1425.66,5,190,Mozambique,Clothing,Saturday,False

In [31]:
df_rs.describe()

,Product ID,Units Sold,Sales Revenue (USD),Discount Percentage,Marketing Spend (USD)
count,3.000000e+04,30000.000000,30000.000000,30000.000000,30000.000000
mean,4.461294e+07,6.161967,2749.509593,2.973833,49.944033
std,2.779759e+07,3.323929,2568.639288,5.974530,64.401655
min,3.636541e+06,0.000000,0.000000,0.000000,0.000000
25%,2.228600e+07,4.000000,882.592500,0.000000,0.000000
50%,4.002449e+07,6.000000,1902.420000,0.000000,1.000000
75%,6.559352e+07,8.000000,3863.920000,0.000000,100.000000
max,9.628253e+07,56.000000,27165.880000,20.000000,199.000000

In [32]:
df_rs.isnull().sum()

Store ID                 0
Product ID               0
Date                     0
Units Sold               0
Sales Revenue (USD)      0
Discount Percentage      0
Marketing Spend (USD)    0
Store Location           0
Product Category         0
Day of the Week          0
Holiday Effect           0
dtype: int64

In [34]:
df_rs.drop_duplicates()

,Store ID,Product ID,Date,Units Sold,Sales Revenue (USD),Discount Percentage,Marketing Spend (USD),Store Location,Product Category,Day of the Week,Holiday Effect
0,Spearsland,52372247,2022-01-01,9,2741.69,20,81,Tanzania,Furniture,Saturday,False
1,Spearsland,52372247,2022-01-02,7,2665.53,0,0,Mauritania,Furniture,Sunday,False
2,Spearsland,52372247,2022-01-03,1,380.79,0,0,Saint Pierre and Miquelon,Furniture,Monday,False
3,Spearsland,52372247,2022-01-04,4,1523.16,0,0,Australia,Furniture,Tuesday,False
4,Spearsland,52372247,2022-01-05,2,761.58,0,0,Swaziland,Furniture,Wednesday,False
...,...,...,...,...,...,...,...,...,...,...,...
29995,Spearsland,50239115,2022-01-25,5,2501.15,0,100,Malawi,Clothing,Tuesday,False
29996,Spearsland,50239115,2022-01-26,3,1500.69,0,0,Sudan,Clothing,Wednesday,False
29997,Spearsland,50239115,2022-01-27,6,3001.38,0,0,South Georgia and the South Sandwich Islands,Clothing,Thursday,False
29998,Spearsland,50239115,2022-01-28,5,2501.15,0,0,Haiti,Clothing,Friday,False
29999,Spearsland,50239115,2022-01-29,3,1425.66,5,190,Mozambique,Clothing,Saturday,False

In [35]:
# change date to datetime
df_rs['Date'] = pd.to_datetime(df_rs['Date'])

In [36]:
df_rs['Year'] = df_rs['Date'].dt.year
df_rs['Month'] = df_rs['Date'].dt.month
df_rs['Day'] = df_rs['Date'].dt.day

In [38]:
df_rs.to_csv('Retail_final.csv', index=False)